name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Flet CLI
        run: |
          python -m pip install --upgrade pip
          pip install flet

      - name: Compilar APK
        run: |
          flet build apk --verbose

      - name: Subir APK generado
        uses: actions/upload-artifact@v4
        with:
          name: App-Marcador-Android
          path: build/apk/*.apk