name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: Instalar Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Instalar Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install flet

      - name: Compilar archivo APK
        run: flet build apk

      - name: Guardar APK generado
        uses: actions/upload-artifact@v4
        with:
          name: App-Marcador-Android
          path: build/apk/*.apk